#!/bin/bash
####################################################################
# Gets the public IP address of current server
# Using checkip.dyndns.org
# yorch (jorge.barnaby {at} gmail.com) - April 2012
####################################################################

cmd='curl -s'
#cmd='wget -q -O'
#cmd='lynx -dump'

#ipservice=whatismyip.org
ipservice=checkip.dyndns.org

pipecmd=(sed -e 's/.*Current IP Address: //' -e 's/<.*$//') #using brackets to use it as an array and avoid need of scaping

# Run command
$cmd "$ipservice" | "${pipecmd[@]}"
